// openanime Provider for Nuvio
// Auto-generated by generate-providers.js — elle düzenleme yapabilirsiniz

var CONFIG_URL = "https://raw.githubusercontent.com/Sezo88/kuki/main/config.json";
var FALLBACK_BASE = "https://openanime.net";

function _getBaseUrl() {
  return fetch(CONFIG_URL)
    .then(function(r) { return r.json(); })
    .then(function(cfg) {
      var p = cfg.providers && cfg.providers["openanime"];
      return (p && p.enabled && p.baseUrl) ? p.baseUrl : FALLBACK_BASE;
    })
    .catch(function() { return FALLBACK_BASE; });
}

function _parseStreams(html, sourceName) {
  var streams = [];
  // iframe linkleri çıkar
  var iframeRe = /iframe[^>]+src=["']([^"']+)["']/gi;
  var m;
  var count = 0;
  while ((m = iframeRe.exec(html)) !== null && count < 5) {
    if (m[1] && m[1].indexOf("http") === 0) {
      streams.push({
        name: sourceName,
        title: "Sunucu " + (count + 1),
        url: m[1],
        quality: count === 0 ? "1080p" : "720p"
      });
      count++;
    }
  }
  // m3u8 linkleri çıkar
  var m3u8Re = /https?:\/\/[^\s"'<>]+\.m3u8[^\s"'<>]*/g;
  var m2;
  var count2 = 0;
  while ((m2 = m3u8Re.exec(html)) !== null && count2 < 3) {
    streams.push({
      name: sourceName,
      title: "HLS " + (count2 + 1),
      url: m2[0],
      quality: "HD"
    });
    count2++;
  }
  return streams;
}

function getStreams(tmdbId, mediaType, season, episode) {
  var label = mediaType === "tv"
    ? "[openanime] S" + season + "E" + episode + " tmdb:" + tmdbId
    : "[openanime] tmdb:" + tmdbId;
  console.log(label);

  return _getBaseUrl().then(function(base) {
    var searchUrl = base + "/?s=" + encodeURIComponent(String(tmdbId));

    return fetch(searchUrl, {
      headers: {
        "User-Agent": "Mozilla/5.0 (Linux; Android 13; Pixel 7) AppleWebKit/537.36",
        "Accept-Language": "tr-TR,tr;q=0.9",
        "Referer": base
      }
    })
    .then(function(r) { return r.text(); })
    .then(function(html) {
      var streams = _parseStreams(html, "openanime");

      // İçerik sayfasına gitmek için ilk post linkini bul
      var linkRe = /href=["'](https?:\/\/[^"']*openanime[^"']+)["']/i;
      var linkMatch = html.match(linkRe);
      if (!linkMatch && streams.length === 0) {
        // Genel link dene
        var genericLink = html.match(/class=["'][^"']*post[^"']*["'][^>]*>\s*<a[^>]+href=["']([^"']+)["']/i);
        if (genericLink) linkMatch = genericLink;
      }

      if (!linkMatch || streams.length > 0) return streams;

      var contentUrl = linkMatch[1];
      // Dizi ise bölüm URL'si dene
      if (mediaType === "tv" && season && episode) {
        var epSuffix = "/sezon-" + season + "-bolum-" + episode;
        contentUrl = contentUrl.replace(/\/?$/, epSuffix);
      }

      return fetch(contentUrl, {
        headers: {
          "User-Agent": "Mozilla/5.0 (Linux; Android 13)",
          "Referer": base
        }
      })
      .then(function(r2) { return r2.text(); })
      .then(function(html2) {
        return _parseStreams(html2, "openanime");
      });
    });
  }).catch(function(err) {
    console.error("[openanime] Hata:", err.message);
    return [];
  });
}

module.exports = { getStreams: getStreams };
